export const strings = {
    analyse: 'Analysieren',
    browse: 'Quellverzeichnis',
    cancel: 'Abbrechen',
    close: 'Schliessen',
    count: (count: number) => `Dateien: ${count}`,
    directory: 'Verzeichnis:',
    loadFrom: 'Import',
    newRule: '(neue Regel)',
    noCategory: '(nicht zugeordnet)',
    remove: 'Entfernen',
    rules: 'Regeln',
    save: 'Speichern',
    saveAs: 'Export',
    select: 'Verwenden',
}
